### ISSUE TITLE
app funktioniert nicht unter Python 2.7(.9)

### ISSUE THREAD

**Issue by nerdoc** [hutchison/bp_mgmt#2]
Unter Ubuntu funktioniert bereits manage.py nicht.
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/christian/.virtualenvs/rotamed/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/christian/.virtualenvs/rotamed/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/home/christian/.virtualenvs/rotamed/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/christian/.virtualenvs/rotamed/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/christian/.virtualenvs/rotamed/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/christian/src/bp_mgmt/bp_mgmt/__init__.py", line 1, in <module>
    from bp_mgmt.celery import app as celery_app
  File "/home/christian/src/bp_mgmt/bp_mgmt/celery.py", line 2, in <module>
    from celery import Celery
```
Siehe http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

PR folgt.

**Comment by nerdoc** [comment]
Python3 ist sinnvoller. Wußte nicht dass das gleich unterstützt ist.
